# Build Stage
FROM node:20-alpine3.19 AS build

WORKDIR /app

RUN apk add --no-cache bash && npm install -g pnpm

COPY package.json ./
RUN pnpm install

COPY . .

RUN pnpm run build


# Production Stage
FROM node:20-alpine3.19 AS production

WORKDIR /app

RUN apk add --no-cache bash && npm install -g pnpm

COPY package.json ./
RUN pnpm install --prod

COPY --from=build /app /app

ENV NODE_OPTIONS=--max-old-space-size=16384
ENV GENERATE_SOURCEMAP=false

CMD pnpm run start

