FROM node:20-alpine3.19

WORKDIR /app

RUN apk add --no-cache bash && npm install -g pnpm

COPY package.json ./

RUN pnpm install

COPY . .

ENV NODE_OPTIONS=--max-old-space-size=16384
ENV GENERATE_SOURCEMAP=false

CMD pnpm run dev
