import type { Metadata } from "next";

import "./globals.css";
import Layout from "@/components/layout";
import 'swiper/css';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-bg p-6">
        <Layout>
        {children}
        </Layout>
      </body>
    </html>
  );
}
