import type { Metadata } from "next";

import "./globals.css";
import Layout from "@/components/layout";
import "swiper/css";
import "swiper/css/free-mode";
import "swiper/css/navigation";
import "swiper/css/thumbs";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-bg p-6">
        <Layout>
        {children}
        </Layout>
      </body>
    </html>
  );
}
